version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.1.4
    ports:
      - "2379:2379"
    hostname: etcd
    command: "etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd:2379"
  kateway:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - KATEWAY_ETCD_ENDPOINTS=http://etcd:2379
      - KATEWAY_ADMIN_TOKEN=secret