version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.1.4
    ports:
      - "2379:2379"
    hostname: etcd
    command: "etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd-1:2379"
